
MOVE = "move"
MOVEREL = "moverel"
CLICK = "click"
WAIT = "wait"
DOUBLECLICK = "doubleclick"
JUMP = "jump"
PRINT = "print"
CENTERMOUSE = "centermouse"
PAUSE = "pause"
GOBACK = "goback"
SETOFFSET = "setoffset"
CLEAROFFSET = "clearoffset"
LABEL = "label"